### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by it-can** [spatie/laravel-sitemap#136]
Hi, I am getting this error when installing this package... on my latest Laravel 5.6 app...

```
php artisan -V
Laravel Framework 5.6.7
```

```
composer require spatie/laravel-sitemap

Using version ^5.0 for spatie/laravel-sitemap
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-sitemap ^5.0 -> satisfiable by spatie/laravel-sitemap[5.0.0].
    - Conclusion: remove laravel/framework v5.6.7
    - Conclusion: don't install laravel/framework v5.6.7
    - spatie/laravel-sitemap 5.0.0 requires spatie/crawler ^4.0 -> satisfiable by spatie/crawler[4.0.0, 4.0.1, 4.0.2, 4.0.3].
    - spatie/crawler 4.0.0 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
    - spatie/crawler 4.0.1 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
    - spatie/crawler 4.0.2 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
    - spatie/crawler 4.0.3 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.4, v5.6.5, v5.6.6, v5.6.7].
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.6.7
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.6.7
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.6.7
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.6.7
    - Can only install one of: laravel/framework[v5.6.0, v5.6.7].
    - Can only install one of: laravel/framework[v5.6.1, v5.6.7].
    - Can only install one of: laravel/framework[v5.6.2, v5.6.7].
    - Can only install one of: laravel/framework[v5.6.3, v5.6.7].
    - don't install tightenco/collect v5.6.0|don't install laravel/framework v5.6.7
    - don't install tightenco/collect v5.6.4|don't install laravel/framework v5.6.7
    - don't install tightenco/collect v5.6.5|don't install laravel/framework v5.6.7
    - don't install tightenco/collect v5.6.6|don't install laravel/framework v5.6.7
    - don't install tightenco/collect v5.6.7|don't install laravel/framework v5.6.7
    - Installation request for laravel/framework (locked at v5.6.7, required as 5.6.x) -> satisfiable by laravel/framework[v5.6.7].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by brendt** [comment]
Hi @it-can ! 

I just released a new version (https://github.com/spatie/laravel-sitemap/releases/tag/5.0.1) which will use the right version of `spatie/crawler`.

You should be able to run a simple `composer up` to update the dependencies correctly. If for some reason you're still getting the `5.0.0` version of sitemap, please run the following command:

```
composer require spatie/laravel-sitemap:^5.0.1
```

**Comment by it-can** [comment]
still not working :-(

**Comment by brendt** [comment]
Could you share your `composer.json` file?

**Comment by it-can** [comment]
```
"require": {
    "php": ">=7.1.3",
    "albertcht/invisible-recaptcha": "^1.8",
    "barryvdh/laravel-dompdf": "^0.8.2",
    "bugsnag/bugsnag-laravel": "^2.14",
    "creitive/laravel5-breadcrumbs": "^2.1",
    "doctrine/dbal": "^2.6",
    "guzzlehttp/guzzle": "^6.3",
    "intervention/image": "^2.4",
    "laracasts/flash": "^3.0",
    "laravel/framework": "5.6.x",
    "laravelcollective/html": "^5.6",
    "laravelista/ekko": "^1.5",
    "league/csv": "^9.1",
    "lukepolo/laracart": "^1.5",
    "mollie/laravel-mollie": "^1.5",
    "morrislaptop/laravel-queue-clear": "^1.1",
    "pragmarx/google2fa": "^1.0",
    "spatie/laravel-failed-job-monitor": "^3.0",
    "spatie/laravel-missing-page-redirector": "^2.2"
  },
  "require-dev": {
    "barryvdh/laravel-debugbar": "^3.1",
    "barryvdh/laravel-ide-helper": "^2.4",
    "filp/whoops": "~2.0",
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "~1.0",
    "nunomaduro/collision": "~2.0",
    "phpunit/phpunit": "~7.0",
    "predis/predis": "^1.1"
  },
```

**Comment by brendt** [comment]
Thanks, hang on a few minutes 🤓

**Comment by freekmurze** [comment]
While you wait, send us a postcard: https://github.com/spatie/laravel-sitemap#postcardware 💌

**Comment by brendt** [comment]
So, @it-can , I tried the following out:

```
"laravel/framework": "~5.6.0",
"spatie/laravel-sitemap": "^5.0.1"
```

Which works on a clean install. This means you'll might have to remove `composer.lock` to reinstall the correct dependencies. I'm not sure if you're able to do that.

The problem, as far as I can tell, happens because of a version conflict in higher versions of `laravel/framework`, two weeks ago this commit was added: https://github.com/laravel/framework/commit/5caa88acde3d8a82fcbb9bbec8dde45dc49d4b7b

So this setup will download `laravel/framework:5.6.3` instead of the latest version; `laravel/framework:5.6.7` as of writing. I'll ask for more input on that commit.

**Comment by brendt** [comment]
For reference, this is the issue on `laravel/framework`: https://github.com/laravel/framework/issues/23366

**Comment by brendt** [comment]
This PR fixes the issue in Laravel: https://github.com/laravel/framework/pull/23379

As states in the comments, if you have Laravel `5.6.4` - `5.6.7` locked as a dependency, you'll not be able to install this package. Furthermore: Laravel `5.6.8` isn't tagged yet, so you either need to:

- Require `laravel/framework:~5.6.0`.
- Manually require `tightenco/collect`, which should fix it according to some tests done by others.
- Wait for `laravel/framework:5.6.8` to release.

**Comment by brendt** [comment]
For reference: as of laravel 5.6.12 this version conflict is fixed.

**Comment by connor11528** [comment]
If you're not on latest Laravel you can do:

```
composer require spatie/laravel-sitemap:4.0
```

Similar to #140 #132 #130

**Comment by rawalprashant** [comment]
I am with Laravel version 8 and still getting the same errors.

**Comment by ProfSteam** [comment]
Same here.
There is my composer.json:

`
    "require": {
        "php": "^7.3|^8.0",
        "butschster/meta-tags": "^2.1",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.5",
        "jeroennoten/laravel-adminlte": "^3.7",
        "laravel/framework": "^8.54",
        "laravel/jetstream": "^2.3",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "laravelcollective/html": "^6.2",
        "livewire/livewire": "^2.5",
        "spatie/laravel-cookie-consent": "^2.12"
    },
`

And the error I get

`
Using version ^5.9 for spatie/laravel-sitemap
./composer.json has been updated
Running composer update spatie/laravel-sitemap
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-sitemap[5.9.0, ..., 5.9.1] require spatie/crawler ^5.0 -> satisfiable by spatie/crawler[5.0.0, 5.0.1, 5.0.2, v5.x-dev].
    - spatie/laravel-sitemap 5.9.2 requires spatie/crawler ^5.0|^6.0 -> satisfiable by spatie/crawler[5.0.0, 5.0.1, 5.0.2, v5.x-dev, 6.0.0, 6.0.1, 6.0.2, v6.x-dev].
    - spatie/crawler[5.0.0, ..., v5.x-dev] require guzzlehttp/psr7 ^1.4 -> found guzzlehttp/psr7[1.4.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - spatie/crawler[6.0.0, ..., v6.x-dev] require guzzlehttp/psr7 ^1.7 -> found guzzlehttp/psr7[1.7.0, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires spatie/laravel-sitemap ^5.9 -> satisfiable by spatie/laravel-sitemap[5.9.0, 5.9.1, 5.9.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

**Comment by Dimchao** [comment]
@ProfSteam delete you composer.lock file (or rename it to save it), and then re-run the "composer require spatie/laravel-sitemap" command in the terminal. This solved the issue on my end and our error messages we the same.

**Comment by JoyJulianGomes** [comment]
I am using 
php: 7.4
laravel: 8.40

I had conflict for guzzlehttp/psr7, which was locked to version 2.0.1 by other packages. All of them had defined the dependecy as `"guzzlehttp/psr7": "^1.7|^2.0",`

So, first i specified the version for guzzlehttp/psr7 to 1.7 in composer.json, 
After `composer update` I could run `composer require spatie/laravel-sitemap`*

* Note: I had to enable `exif` extension

**Comment by Icrmsoftware** [comment]
> 

Thank you! This is the easiest solution i found.
